language: php

sudo: required

services:
  - docker

matrix:
  fast_finish: true
  include:
  - php: 7.1.3
    env: TESTBENCH_VERSION=3.8.3
  - php: 7.2
    env: TESTBENCH_VERSION=3.8.3
  - php: 7.3
    env: TESTBENCH_VERSION=3.8.3

before_script:
  - travis_retry composer update --prefer-dist --no-interaction --prefer-stable --no-suggest
  - travis_retry composer require --no-interaction --prefer-stable --no-suggest --update-with-dependencies --dev "orchestra/testbench:${TESTBENCH_VERSION}"

script:
  - docker pull localstack/localstack
  - HOSTNAME_EXTERNAL=http://localhost:4576
  - echo $HOSTNAME_EXTERNAL
  - docker-compose up -d & sleep 20
  - composer validate
  - vendor/bin/phpunit
