language: php

sudo: required

matrix:
  enclude:
  - php: 7.0
    env: TESTBENCH_VERSION=3.5.*
    env: PHPUNIT_VERSION=6.0
  - php: 7.1.3
    env: TESTBENCH_VERSION=3.6.*
    env: PHPUNIT_VERSION=7.0
  - php: 7.1.3
    env: TESTBENCH_VERSION=3.7.*
    env: PHPUNIT_VERSION=7.5
  - php: 7.1.3
    env: TESTBENCH_VERSION=3.8.*
    env: PHPUNIT_VERSION=7.5
  - php: 7.2
    env: TESTBENCH_VERSION=3.8.*
    env: PHPUNIT_VERSION=8.0
    
services:
  - docker

before_script:
  - travis_retry composer self-update
  - travis_retry composer require --prefer-source --no-interaction --dev "orchestra/testbench:${TESTBENCH_VERSION}"
  - travis_retry composer require --prefer-source --no-interaction --dev "phpunit/phpunit:${PHPUNIT_VERSION}"

script:
  - docker pull localstack/localstack
  - docker-compose up -d & sleep 20
  - composer validate
  - vendor/bin/phpunit
